server:
  port: 8082

spring:
  application:
    name: catalog-inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: nikil

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg==